# Utiliser l'image Nginx Alpine comme base
FROM nginx:alpine

# Copier les fichiers statiques dans le dossier de travail de Nginx
COPY ./project /usr/share/nginx/html

# Exposer le port (par exemple, 80)
EXPOSE 80